/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as AdminRouteImport } from './app/_admin'
import { Route as AdminIndexRouteImport } from './app/_admin/index'
import { Route as AdminClientesIndexRouteImport } from './app/_admin/clientes/index'
import { Route as AdminAssinaturasIndexRouteImport } from './app/_admin/assinaturas/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as AdminAssinaturasNovaRouteImport } from './app/_admin/assinaturas/nova'
import { Route as AdminAssinaturasIdRouteImport } from './app/_admin/assinaturas/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasIndexRoute = AdminAssinaturasIndexRouteImport.update({
  id: '/assinaturas/',
  path: '/assinaturas/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssinaturasNovaRoute = AdminAssinaturasNovaRouteImport.update({
  id: '/assinaturas/nova',
  path: '/assinaturas/nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasIdRoute = AdminAssinaturasIdRouteImport.update({
  id: '/assinaturas/$id',
  path: '/assinaturas/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/assinaturas/$id': typeof AdminAssinaturasIdRoute
  '/assinaturas/nova': typeof AdminAssinaturasNovaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/assinaturas/': typeof AdminAssinaturasIndexRoute
  '/clientes/': typeof AdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AdminIndexRoute
  '/assinaturas/$id': typeof AdminAssinaturasIdRoute
  '/assinaturas/nova': typeof AdminAssinaturasNovaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/assinaturas': typeof AdminAssinaturasIndexRoute
  '/clientes': typeof AdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/assinaturas/$id': typeof AdminAssinaturasIdRoute
  '/_admin/assinaturas/nova': typeof AdminAssinaturasNovaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/assinaturas/': typeof AdminAssinaturasIndexRoute
  '/_admin/clientes/': typeof AdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assinaturas/$id'
    | '/assinaturas/nova'
    | '/api/auth/$'
    | '/assinaturas/'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/assinaturas/$id'
    | '/assinaturas/nova'
    | '/api/auth/$'
    | '/assinaturas'
    | '/clientes'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/'
    | '/_admin/assinaturas/$id'
    | '/_admin/assinaturas/nova'
    | '/api/auth/$'
    | '/_admin/assinaturas/'
    | '/_admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clientes/': {
      id: '/_admin/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/assinaturas/': {
      id: '/_admin/assinaturas/'
      path: '/assinaturas'
      fullPath: '/assinaturas/'
      preLoaderRoute: typeof AdminAssinaturasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/assinaturas/nova': {
      id: '/_admin/assinaturas/nova'
      path: '/assinaturas/nova'
      fullPath: '/assinaturas/nova'
      preLoaderRoute: typeof AdminAssinaturasNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/assinaturas/$id': {
      id: '/_admin/assinaturas/$id'
      path: '/assinaturas/$id'
      fullPath: '/assinaturas/$id'
      preLoaderRoute: typeof AdminAssinaturasIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssinaturasIdRoute: typeof AdminAssinaturasIdRoute
  AdminAssinaturasNovaRoute: typeof AdminAssinaturasNovaRoute
  AdminAssinaturasIndexRoute: typeof AdminAssinaturasIndexRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAssinaturasIdRoute: AdminAssinaturasIdRoute,
  AdminAssinaturasNovaRoute: AdminAssinaturasNovaRoute,
  AdminAssinaturasIndexRoute: AdminAssinaturasIndexRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
